//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetris
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCORETETRIS
    {
        public int idPlayer { get; set; }
        public string PlayerName { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Score { get; set; }
    }
}
